# .platform.app.yaml for React frontend
name: adriatic-mini-booking-frontend
type: nodejs:20

build:
  flavor: none

variables:
  env:
    NODE_ENV: "production"
    REACT_APP_BASE_API_URL: "https://{default}/api"

dependencies:
  nodejs:
    react-scripts: "^4.0.0"

hooks:
  build: |
    npm install
    npm run build

web:
  locations:
    "/":
      root: "build"
      passthru: "/index.html"
      allow: true

mounts:
  "/build": "shared:files/frontend/build"
