# .platform.app.yaml for PHP backend
name: adriatic-mini-booking-backend
type: "php:8.3"

web:
  locations:
    "/":
      root: "public"
      index: ["index.php"]

mounts:
  "/public": "shared:files/backend/public"
