adriatic-mini-booking-backend:
  type: php:8.2

  web:
    locations:
      "/api":
        root: "public"
        passthru: "/api/index.php"
        index:
          - index.php
        headers:
          Access-Control-Allow-Origin: "*"

  disk: 128

  mounts:
    "/data-write":
      source: tmp

  source:
    root: backend

adriatic-mini-booking-frontend:
  type: nodejs:20

  web:
    locations:
      "/":
        root: "frontend/build"
        passthru: "/index.html"
        index:
          - "index.html"
        headers:
          Access-Control-Allow-Origin: "*"
