# routes.yaml
"https://{default}/":
  type: upstream
  upstream: "adriatic-mini-booking-frontend:http"

"https://{default}/api":
  type: upstream
  upstream: "adriatic-mini-booking-backend:php"
  cache:
    enabled: false
